# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

  formatting:
    name: check-fmt
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install npm
        uses: actions/setup-node@v2
      - name: Install eclint
        run: npm install -g lintspaces-cli
      - name: Run Formatter
        run: lintspaces -e .editorconfig -i 'java-comments' ./src/main/**/*.java
